export const PAGES_ROUTE_CONFIG = {
  HOME: {
    name: 'oxic каталог',
    route: '/',
    handler: 'catalog',
    loginRequired: false,
    logoutRequired: false,
    pattern: /^\/$/,
  },
  CATALOG: {
    name: 'oxic каталог',
    route: '/catalog',
    handler: 'catalog',
    loginRequired: false,
    logoutRequired: false,
    pattern: /^\/catalog$/,
  },
  ORDER_LIST: {
    name: 'Заказы',
    route: '/order_list',
    handler: 'order_list',
    loginRequired: true,
    logoutRequired: false,
    pattern: /^\/order_list$/,
  },
  CHANGE_CITY: {
    name: 'Поменять город',
    route: '/change_city',
    handler: 'changeCity',
    loginRequired: false,
    logoutRequired: false,
    pattern: /^\/change_city$/,
  },
  CART: {
    name: 'Корзина',
    route: '/cart',
    handler: 'cart',
    loginRequired: true,
    logoutRequired: false,
    pattern: /^\/cart$/,
  },
  FAVORITE: {
    name: 'Избранное',
    route: '/favorites',
    handler: 'favorites',
    loginRequired: true,
    logoutRequired: false,
    pattern: /^\/favorites$/,
  },
  PRODUCT: {
    name: '',
    route: '/product/:id',
    handler: 'product',
    loginRequired: false,
    logoutRequired: false,
    pattern: /^\/product\/\d+$/,
  },
  LOGOUT: {
    name: 'Выход из oxic =(',
    route: '/logout',
    handler: 'logout',
    loginRequired: true,
    logoutRequired: false,
    pattern: /^\/logout$/,
  },
  SIGNUP: {
    name: 'Регистрация в oxic =)',
    route: '/signup',
    handler: 'signup',
    loginRequired: false,
    logoutRequired: true,
    pattern: /^\/signup$/,
  },
  LOGIN: {
    name: '',
    route: '/login',
    handler: 'login',
    loginRequired: false,
    logoutRequired: true,
    pattern: /^\/login$/,
  },
  ACCOUNT: {
    name: '',
    route: '/account',
    handler: 'account',
    loginRequired: true,
    logoutRequired: false,
    pattern: /^\/account$/,
  },
  ERROR: {
    name: '',
    route: '/error/404',
    handler: 'error',
    loginRequired: false,
    logoutRequired: false,
    pattern: /^\/error\/404$/,
  },
};