name: Kotyari Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Checkout code
        run: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: 94.139.246.241
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/dist"
          strip_components: 1
